import enum
from dataclasses import dataclass, field
from typing import Any, Dict, List, NamedTuple, Set

import pyomo.environ as pyo

from coral.breakpoint.breakpoint_graph import BreakpointGraph


@dataclass
class EdgeToCN:
    """Container class for mapping edge indices (by type) to CN (copy number) values."""

    sequence: Dict[int, float] = field(default_factory=dict)
    concordant: Dict[int, float] = field(default_factory=dict)
    discordant: Dict[int, float] = field(default_factory=dict)
    source: Dict[int, float] = field(default_factory=dict)

    @staticmethod
    def from_graph(bp_graph: BreakpointGraph):
        return EdgeToCN(
            sequence={
                i: edge[-1] for i, edge in enumerate(bp_graph.sequence_edges)
            },
            concordant={
                i: edge[-1] for i, edge in enumerate(bp_graph.concordant_edges)
            },
            discordant={
                i: edge[-1] for i, edge in enumerate(bp_graph.discordant_edges)
            },
            source={
                i: edge[-1] for i, edge in enumerate(bp_graph.source_edges)
            },
        )


@dataclass
class ParsedLPSolution:
    """Container for storing MIQCP solution state, solved cycles (+weights), and satisfied path constraints."""

    solver_status: str
    termination_condition: pyo.TerminationCondition
    total_weights_included: float = 0.0
    walks: List[List[Any]] = field(
        default_factory=lambda: [[], []]
    )  # cycles, paths
    walk_weights: List[List[Any]] = field(
        default_factory=lambda: [[], []]
    )  # cycles, paths
    path_constraints_satisfied: List[List[Any]] = field(
        default_factory=lambda: [[], []]
    )  # cycles, paths
    path_constraints_satisfied_set: Set[int] = field(default_factory=set)

    @property
    def num_pc_satisfied(self) -> int:
        return len(self.path_constraints_satisfied_set)


class InitialSolution(NamedTuple):
    """Container for storing initial solution state (generated by a heuristic method or incomplete solver run), to be passed to another model."""

    cycles: List
    cycle_weights: List
    satisfied_path_constraints: List


class Solver(str, enum.Enum):
    """Enum for specifying the solver to pass to the MIQCP model used for cycle identification."""

    GUROBI = "gurobi"
    SCIP = "scip"
    # Coin-OR solvers
    BONMIN = "bonmin"
    COUENNE = "couenne"
